#! /bin/sh
# gen_dev 1

NAME=$1
N=${NAME##dev}

TEMPLATE="./rel/vars/dev_vars.config.src"
OUTPUT="./rel/vars/"$NAME"_vars.config"
BASE_PORT=5000

NODE="'$NAME@127.0.0.1'"
PORT=$((BASE_PORT + $N - 1))

echo "Generating $NAME node ( $NODE $PORT )"
sed -e "s/@NODE@/$NODE/" \
    -e "s/@PORT@/$PORT/" < $TEMPLATE > $OUTPUT
